GitLabAPI/GitLabAPI/src/objects/Sensor__c.object
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor_Event (Sensor)</relationshipLabel>
        <relationshipName>Sensor_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/classes/RestAPIClassTest.cls
@IsTest
private class RestAPIClassTest
{
    static testMethod void testPostMethod()
    {
        RestRequest request = new RestRequest();
        request.requestUri ='https://sergeizhugin-developer-edition.ap4.force.com/services/apexrest/Sensor';
        request.httpMethod = 'POST';
        RestContext.request = request;
        
        Integer[] coordsArray_01 = new Integer[]{1,2,3,4,5,6,7,8,9,0,11,22};
        String testWorkspace_01 = SmartWorkSpace.createSensor('1001', coordsArray_01);
        Sensor__c sensorTest_01 = [SELECT (select id, x__c, y__c, z__c FROM Sensor_Events__r ) FROM Sensor__c WHERE Name = '1001'];
        System.assertEquals(1, sensorTest_01.Sensor_Events__r[0].x__c);
        System.assertEquals('Sensor created successfully', testWorkspace_01);
        
        Integer[] coordsArray_02 = new Integer[]{1000,2,3,4,5,6,7,8,9,0,11,22};
        String testWorkspace_02 = SmartWorkSpace.createSensor('1001', coordsArray_02);
        Sensor__c sensorTest_02 = [SELECT (select id, x__c, y__c, z__c FROM Sensor_Events__r ) FROM Sensor__c WHERE Name = '1001'];
        System.assertEquals(1000, sensorTest_02.Sensor_Events__r[0].x__c);
        System.assertEquals('Sensor created successfully', testWorkspace_02);
        
        Integer[] coordsArray_03 = new Integer[]{1000,100,3,4,5,6,7,8,9,0,11,22,99};
        String testWorkspace_03 = SmartWorkSpace.createSensor('1001', coordsArray_03);
        System.assertEquals('ERROR: Check number of coords', testWorkspace_03);
    }
}