GitLabAPI/GitLabAPI/src/objects/Sensor__c.object
<CustomObject>
    <fields>
        <fullName>Max_Vectors_Difference__c</fullName>
        <label>Max_Vectors_Difference</label>
        <summarizedField>Sensor_Event__c.Modulus_difference_Vectors__c</summarizedField>
        <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sensor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor_Event (Sensor)</relationshipLabel>
        <relationshipName>Sensor_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/classes/ApplicationController.cls
public with sharing class ApplicationController {
    
    public class fieldWrapper {
        string xc;
        string yc;
        string zc;
    }
    
	@AuraEnabled       
    public static List<String> OutputPicklist(){
       	List<Sensor__c> sensors = [SELECT Name FROM Sensor__c LIMIT 50];    
        Set<string> setSensorsName = new Set<string>();
        for(Sensor__c item : sensors) {
            setSensorsName.add(item.Name);
        }
		List<string> picklistName = new List<string>();
        for(String item : setSensorsName) {
            picklistName.add(item);
        }
        return picklistName;
    }  
    @AuraEnabled
	public static Sensor__c ViewName(String recordName){
		Sensor__c sensor = [SELECT Name, Max_Vectors_Difference__c
                       FROM Sensor__c
                       WHERE Name =:recordName];
        return sensor;
	}
	@AuraEnabled
	public static Sensor_Event__c[] ViewEvents(String recordName){
		Sensor__c sensor = [SELECT (select id, x__c, y__c, z__c FROM Sensor_Events__r )
                       FROM Sensor__c
                       WHERE Name =:recordName];
        return sensor.Sensor_Events__r;
	}
    @AuraEnabled
	public static Sensor_Event__c[] UpdateEvents(string recordName, string JSONstring){
    	Sensor__c sensor = [SELECT Name,Max_Vectors_Difference__c, (select id, x__c, y__c, z__c FROM Sensor_Events__r )
                       FROM Sensor__c
                       WHERE Name =:recordName];
       	delete sensor.Sensor_Events__r;

       	List<Sensor_Event__c> listEvent = new List<Sensor_Event__c>();
        List<fieldWrapper> listWrapper = (List<fieldWrapper>) JSON.deserialize(JSONstring, List<fieldWrapper>.class);
        for(fieldWrapper wrapper: listWrapper) {
        	Sensor_Event__c sensorEvent = new Sensor_Event__c();
            sensorEvent.x__c = decimal.valueOf(wrapper.xc);
            sensorEvent.y__c = decimal.valueOf(wrapper.yc);
            sensorEvent.z__c = decimal.valueOf(wrapper.zc);
            sensorEvent.Sensor__c = sensor.Id;
            listEvent.add(sensorEvent);
		}
       	insert listEvent;
        return sensor.Sensor_Events__r;
	}
}