GitLabAPI/GitLabAPI/src/objects/Sensor__c.object
<CustomObject>
    <fields>
        <fullName>Max_Vectors_Difference__c</fullName>
        <label>Max_Vectors_Difference</label>
        <summarizedField>Sensor_Event__c.Modulus_difference_Vectors__c</summarizedField>
        <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sensor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor_Event (Sensor)</relationshipLabel>
        <relationshipName>Sensor_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GitLabAPI/GitLabAPI/src/classes/SmartWorkSpace.cls
@RestResource(urlMapping='/Sensor/*')
global with sharing class SmartWorkSpace {
    @HttpPost
	global static string createSensor(String sensorid, Integer[] line) {
        string returnString = 'Sensor created successfully';
        if(line.size() != 12) {
            returnString = 'ERROR: Check number of coords';
            return returnString;
        }
   		List<Sensor__c> sensor = [SELECT Name, Max_Vectors_Difference__c, (select id, x__c, y__c, z__c FROM Sensor_Events__r )
                       FROM Sensor__c
                       WHERE Name =:sensorid];
    	if(!sensor.isEmpty()) {
			delete sensor[0].Sensor_Events__r;
        	update sensor;
		}
        else {
        	sensor.add(new Sensor__c());
            sensor[0].Name = sensorid;
            insert sensor;
      	}
        List<Sensor_Event__c> eveList = new List<Sensor_Event__c>();
        Sensor_Event__c eve = new Sensor_Event__c();
        integer iteration = 0;
        for(integer i = 0; i<line.size()/3;i++) {
        	eve.x__c = line[iteration];
            eve.y__c = line[iteration+1];
            eve.z__c = line[iteration+2];
            eve.Sensor__c = sensor[0].Id;
            iteration += 3;
            eveList.add(eve);
           	eve = new Sensor_Event__c();
		}
       	insert eveList;          
        return returnString;
    }
}